services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: >
      sh -c "until python manage.py migrate; do
      echo 'Waiting for database...';
      sleep 2;
      done;
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./frontend

    container_name: frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    stdin_open: true
    tty: true

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: pr_reviewer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pr_reviewer_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./backend
    container_name: celery
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_started

volumes:
  postgres_data:

